# Generated by Django 2.1 on 2019-01-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_teacher_is_repassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_repassword',
            new_name='re_repassword',
        ),
    ]
