# Generated by Django 2.1 on 2019-01-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0004_resourceroleaction_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceroleaction',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
