# Generated by Django 2.1 on 2019-01-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0005_resourceroleaction_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceroleaction',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
