# Generated by Django 2.1 on 2019-01-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0006_auto_20190102_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceroleaction',
            unique_together={('role', 'action', 'resource')},
        ),
    ]
