# Generated by Django 2.1 on 2019-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='匿名', max_length=100),
        ),
    ]
