# Generated by Django 2.1 on 2019-01-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0010_waitsendstudentsms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitsendstudentsms',
            old_name='context',
            new_name='content',
        ),
    ]
