# Generated by Django 2.1 on 2019-01-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0011_auto_20190103_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitsendstudentsms',
            name='questionnaire_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Questionnaire'),
            preserve_default=False,
        ),
    ]
