# Generated by Django 2.1 on 2019-01-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0013_waitsendstudentsms_success_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='re_repassword',
            new_name='re_password',
        ),
        migrations.AlterUniqueTogether(
            name='cityschool',
            unique_together={('city_obj', 'school_obj')},
        ),
    ]
