# Generated by Django 2.1 on 2019-01-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0014_auto_20190104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='xx', help_text='账户名', max_length=20),
        ),
    ]
