# Generated by Django 2.1.4 on 2019-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0015_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='sms_status',
            field=models.BooleanField(default=False),
        ),
    ]
