# Generated by Django 2.1.4 on 2019-01-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0016_questionnaire_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
