# Generated by Django 2.1.4 on 2019-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0017_questionnaire_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetype',
            name='type_name',
            field=models.CharField(help_text='添加问卷类型[例如学生问卷家长问卷]', max_length=50, unique=True),
        ),
    ]
