# Generated by Django 2.0 on 2019-02-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190224_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='models',
            new_name='mobile',
        ),
    ]
