# Generated by Django 2.0 on 2019-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190224_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='validate_sign',
            field=models.CharField(default=1234567, max_length=20),
            preserve_default=False,
        ),
    ]
